name: Test action

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Scan
        uses: silas-x/cfx-action@main
