name: 'Example server owner action'

on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        
      - name: 'Detect keys'
        uses: silas-x/cfx-action@main
